[package]
description = "nu shell plugin to convert a HTTP server sent event stream to structured data"
edition = "2021"
license = "MIT"
name = "nu_plugin_from_sse"
version = "0.0.1"

[[bin]]
name = "nu_plugin_from_sse"

[dependencies]
nu-plugin = "0.91"
nu-protocol = { version = "0.91", features = ["plugin"] }
