[package]
description = "nu shell plugin to convert a HTTP server sent event stream to structured data"
edition = "2021"
license = "MIT"
name = "nu_plugin_from_sse"
version = "0.0.1"

[[bin]]
name = "nu_plugin_from_sse"

[dependencies]
itertools = "0.12.1"
nu-plugin = { path = "../nushell/crates/nu-plugin", version = "0.90.2" }
nu-protocol = { path = "../nushell/crates/nu-protocol", version = "0.90.2", features = ["plugin"] }
